---
- name: Report on shared folders | {{ server }}
  register: r_folder_sizes
  ansible.windows.win_powershell:
    script: "{{ lookup('template', playbook_dir + '/templates/get_share_stats.ps1.j2') }}"

- name: Print stats
  ansible.builtin.debug:
    msg: "{{ r_folder_sizes.result }}"
