---
- name: Create directories
  tags: setup
  loop: "{{ folders }}"
  ansible.windows.win_file:
    path: "{{ root_folder_path }}\\{{ item }}"
    state: directory

- name: Create directory structure
  tags: setup
  loop: "{{ folders }}"
  loop_control:
    label: "{{ root_folder_path }}\\{{ folders[-1] }}\\{{ item }}"
  ansible.windows.win_file:
    path: "{{ root_folder_path }}\\{{ folders[-1] }}\\{{ item }}"
    state: directory

- name: Create some files
  tags: setup
  loop:
    - file1.txt
    - file2.txt
    - file3.txt
  ansible.windows.win_copy:
    content: "Test file for deletion: {{ item }}"
    dest: "{{ root_folder_path }}\\{{ folders[-1] }}\\{{ folders[-1] }}\\{{ item }}"
    state: present
