---
- name: Prep a Proxmox Windows VM for decommissioning
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true

  tasks:
    - name: Add comment | init decomm prep
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: Prepping {{ inventory_hostname }} for decomm process

    - name: Add comment | interface facts
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h3>Network Interface Facts</h3>[/code]{{ hostvars[inventory_hostname]['ansible_interfaces'] | to_nice_json | codify }}"

    - name: Describe instance | smb shares
      register: r_smb_shares
      ansible.windows.win_powershell:
        script: Get-SmbShare | ConvertTo-Json

    - name: Add comment | smb shares
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h3>SMB Share Facts</h3>[/code]{{ r_smb_shares.output[0] | from_json | to_nice_json | codify }}"

    - name: Describe instance | SQL Server
      register: r_sql_server
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL

    - name: Add comment | sql server
      when: r_sql_server.exists
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h3>SQL Facts</h3>[/code]{{ r_sql_server.properties | to_nice_json | codify }}"

    - name: Add comment | sql server
      when: not r_sql_server.exists
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: SQL Server not installed on this machine

    - name: Describe instance | proxmox snapshot
      ansible.builtin.include_role:
        name: mgmt.pve.proxmox_kvm_decomm
      vars:
        proxmox_kvm_decomm_name: "{{ inventory_hostname.split('.')[0] }}"

    - name: Add comment | proxmox snapshot
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: "[code]<h3>Proxmox Facts</h3>[/code]{{ proxmox_kvm_decomm_data | to_nice_json | codify }}"

    - name: Disable AD object
      tags: ad_disable
      delegate_to: "{{ domain_controller | default('dc01.AUTODOTES.LOCAL') }}"
      community.windows.win_domain_computer:
        name: "{{ inventory_hostname.split('.')[0] }}"
        enabled: false

    - name: Determine grace period expiration date
      delegate_to: localhost
      ansible.builtin.set_fact:
        grace_exp_date: "{{ lookup('pipe', 'date -d \"+30 days\" +\"%Y-%m-%d\"') }}"

    - name: Add comment | Initiate grace period
      ansible.builtin.include_tasks:
        file: tasks/snow_comment.yml
      vars:
        snow_comment: >
          [code]<h3>Initiating Grace Period</h3>[/code]
          Grace period ends on {{ grace_exp_date }}
