---
- name: Install SQL Server on Window host
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Install MSSQL using DSC
      tags: always
      ansible.builtin.include_role:
        name: mgmt.windows.mssql
      vars:
        netbios: AUTODOTES
        domain_controller: dc01.AUTODOTES.LOCAL
        mssql_base_ldap_path: OU=Users,OU=lab,DN=autodotes,DN=local

        ### From custom credential ###
        # mssql_sqlsvc_account_pass:
        # mssql_agentsvc_account_pass
        # mssql_assvc_account_pass:
