---
- name: Leave domain
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false

  vars:
    domain_controller: dc01.AUTODOTES.LOCAL

  tasks:
    - name: Wait for target to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Disable ipv6
      ansible.windows.win_powershell:
        script: Disable-NetAdapterBinding -Name 'Ethernet Instance 0' -ComponentId ms_tcpip6

    - name: Reconfigure default DNS
      ansible.windows.win_dns_client:
        adapter_names: Ethernet*
        dns_servers:
          - 192.168.0.1

    - name: Leave Autodotes domain
      throttle: 1
      block:
        - name: Remove legacy dns entries
          delegate_to: "{{ domain_controller }}"
          register: r_dns_entry
          loop: [A, AAAA]
          loop_control:
            loop_var: type
          community.windows.win_dns_record:
            name: "{{ inventory_hostname.split('.')[0] }}"
            type: "{{ type }}"
            zone: "{{ win_domain }}"
            state: absent

        - name: Remove object from domain
          delegate_to: "{{ domain_controller }}"
          microsoft.ad.computer:
            name: "{{ inventory_hostname.split('.')[0] }}"
            state: absent

    - name: Remove host from windows group
      delegate_to: localhost
      ansible.builtin.include: tasks/remove_host_from_group.yml
      vars:
        group_name: windows
        group_inventory: Proxmox Inventory
