---
- name: Create AD groups
  hosts: "{{ domain_controller }}"
  gather_facts: false

  vars:
    search_root: DC=autodotes,DC=com
    servers: |
      win11-guest-1
      win11-guest-2
    server_list: "{{ servers.strip('\n').split('\n') }}"
    # server_list: "{{ lookup('file', playbook_dir + '/files/server_list.txt').strip('\n').split('\n') }}"

  tasks:
    - name: Get stats for each share
      loop: "{{ server_list }}"
      loop_control:
        loop_var: server
      ansible.builtin.include_tasks:
        file: tasks/get_share_stats.yml
