---
- name: Use Ansible to maintain desired state of AD groups
  hosts: domain_controller
  gather_facts: false

  tasks:
    - name: Create Ansible User Group
      ansible.windows.win_group:
        name: Ansible Users
        description: Users created by Ansible product demos Create Domain job
        state: present

    - name: Ensure group matches desired state (membership)
      win_group_membership_mod:
        name: Ansible Users
        members:
          - ANSIBLE\UserA
          - ANSIBLE\UserX
        state: pure
        ignore_invalid: true

    ### Example return object ###

    # {
    #     "added": [
    #         "ANSIBLE\\UserA"
    #     ],
    #     "changed": true,
    #     "invalid": [
    #         "ANSIBLE\\UserX"
    #     ],
    #     "members": [
    #         "ANSIBLE\\UserA"
    #     ],
    #     "name": "Ansible Users",
    #     "removed": []
    # }
